;this file for FamiTone2 library generated by text2data tool

ft2testsong_music_data:
	db 1
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; main song

@instruments:
	db $30 ;instrument $00
	dw @env1,@env0,@env0
	db $00
	db $30 ;instrument $01
	dw @env2,@env0,@env3
	db $00

@samples:
@env0:
	db $c0,$00,$00
@env1:
	db $cf,$ca,$c8,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$03,$c1,$02,$c1,$00,$0d
@env2:
	db $cf,$c6,$c0,$00,$02
@env3:
	db $ff,$80,$80,$00,$02


; main song
@song0ch0:
	db $fb,$06
@song0ch0loop:
@ref0:
	db $80,$4a,$89,$41,$44,$85,$41,$45,$55,$51,$4e,$85,$55,$51,$55,$50
	db $81
@ref1:
	db $4a,$89,$41,$44,$85,$41,$44,$85,$51,$4e,$85,$49,$4b,$4f,$50,$81
	db $fd
	dw @song0ch0loop

; main song
@song0ch1:
@song0ch1loop:
@ref2:
	db $bf
@ref3:
	db $bf
	db $fd
	dw @song0ch1loop

; main song
@song0ch2:
@song0ch2loop:
@ref4:
	db $bf
@ref5:
	db $bf
	db $fd
	dw @song0ch2loop

; main song
@song0ch3:
@song0ch3loop:
@ref6:
	db $82,$03,$21,$09,$21,$03,$21,$21,$21,$03,$21,$09,$21,$03,$21,$09
	db $20,$81
@ref7:
	db $03,$21,$09,$21,$03,$21,$21,$21,$03,$21,$09,$21,$03,$21,$09,$20
	db $81
	db $fd
	dw @song0ch3loop

; main song
@song0ch4:
@song0ch4loop:
@ref8:
	db $bf
@ref9:
	db $bf
	db $fd
	dw @song0ch4loop
